default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: account_management_development

test:
  <<: *default
  database: account_management_test

production:
  <<: *default
  database: account_management_production
  username: account_management
  password: <%= ENV['ACCOUNT_MANAGEMENT_DATABASE_PASSWORD'] %>
